### ISSUE TITLE
Not Icon Tray on KDE Plasma

### ISSUE THREAD

**Issue by ssergio-ll** [ShadyThGod/altus#17]
Hello. I have seen a bug of Altus with KDE Plasma. This don't show icon on tray system. Also don't show icon app of application.

**Comment by ShadyThGod** [comment]
Unfortunately, this is probably something that I can not fix because of the sheer variety of linux distributions and how Electron handles them. If you don't know the tray icon is handled by Electron, so there isn't much I can do. Also, Linux has had issues with icons on any Electron app. I am sorry, but I can't fix this.
