### ISSUE TITLE
Multiple-Monitor Issue

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ShadyThGod/altus#20]
I am using 3 monitors and always had WhatsApp on my right one. Whenever I drag Altus to my right monitor and either restart my PC or play a game in full screen (tested with Minecraft in custom resolution and Civilization V), Altus goes to my middle monitor (in Windows set as main display) or just disappears (?).
Is there a way, that Altus can "remember" the display it was on last time?
Because whenever I start playing any game, I can't look on my WhatsApp messages.

**Comment by ShadyThGod** [comment]
I can make Altus remember the last position before it gets closed and when it opens, make it have the same position. But in your issue, it doesn't seem like that's what's happening.

I will add a setting so it remembers the last position, and then you can let me know if that fixes it. I don't really have any means to test this as I only have a single monitor. I'll release a fix by tomorrow or day after tomorrow. Today, I am a bit busy with personal stuff, hope you can understand.

**Comment by ThexXTURBOXx** [comment]
Okay, thank you very much!

**Comment by ShadyThGod** [comment]
While I am working on implementing the code I spoke about, you might want to try out this software I found.

It's called [Actual Window Manager](https://www.actualtools.com/windowmanager/) which I found from this [Superuser forum post about remembering window size and position](https://superuser.com/questions/639100/solution-to-remember-a-windows-size-and-position-for-laptop-built-in-monitor-vs). This might help in what you want.

Also, if you could, would you please somehow record the issue happening so I can get a better idea of it. Since we're talking about multiple screens here, you might want to use your mobile to record it.

**Comment by ThexXTURBOXx** [comment]
I recorded the issue here: http://femtopedia.de/VID_20190418_101934.mp4
I will try the software in a few minutes and see, whether it helps.
Also, I noticed, that this only seems to be the case in games with custom full screen resolution (e.g. playing a game in 2k on my 4k monitor, lik Minecraft in the video)

**Comment by ShadyThGod** [comment]
This could be an issue with how Windows handles multiple screens. Unfortunately, I don't really see how I might be able to fix this, honestly. What I was going to try was remembering the position when the app exits and when re-opened it stays in that position. However, the app doesn't seem to exit when you go fullscreen, it just disappears. Right now, I don't think there's any way I will be able to detect resolution changes made due to a game going fullscreen and then make subsequent changes to fix that. I could detect changes in the size/resolution of the app itself and try to do something, but that will then not allow other users to change the sizing of the app.

**Comment by ThexXTURBOXx** [comment]
Hm, okay... I already thought something like that unfortunately :/
The software you mentioned, doesn't work unfortunately, too.
I will tinker a little bit around and when I find out, something works, I will let you know, so that everyone having the same problem can fix that, too.

**Comment by ShadyThGod** [comment]
Sorry that I can't help.

I will keep this issue open until you tell otherwise. If you can find something, do post here.

**Comment by ThexXTURBOXx** [comment]
No problem, but I found one thing, that could maybe be related to this issue:
Whenever Altus autostarts with the system, it always starts on the main monitor (in my case the middle one) instead of the last monitor, it was on (the right one).
I didn't find a solution for this issue yet, but I thought, maybe this is related

**Comment by ShadyThGod** [comment]
In [v2.3.0](https://github.com/ShadyThGod/altus/releases/tag/2.3.0), I have made it so the app remembers the app size and position when closing, and then uses the size and position when opened the next time.

**Comment by ThexXTURBOXx** [comment]
Very nice, thank you! I will test it on tuesday, when I'm home

**Comment by ThexXTURBOXx** [comment]
Okay, I tried it, but it opened on the wrong monitor again.
Other apps like e.g. Spotify work though.

**Comment by ShadyThGod** [comment]
Well, I don't think I'm doing anything specifically in my code that is causing this. It could just be something with Electron. Do you use any other Electron base app? Maybe that can help me determine if it's fault at my end or is it Electron.

**Comment by ThexXTURBOXx** [comment]
I've tried two other apps (GitHub Desktop and MongoDB Compass) and both don't seem to work as well. MongoDB Compass always starts with the same size on the main monitor and GitHub Desktop at least saves its size or if it's maximized. If it's maximized, it starts maximized on the main monitor and if it isn't, it starts on the right monitor with the same size. So, it has only a problem with the maximized state.

**Comment by ShadyThGod** [comment]
I think this is Electron behaviour. Don't think it's intended. So you might want to open an issue on the [electron](https://github.com/electron/electron/issues) repository.

**Comment by ThexXTURBOXx** [comment]
Okay, I will do that. Thank you for your help! ^^

**Comment by ShadyThGod** [comment]
BTW, may I interest you to join the [Altus Discord Server](https://discord.gg/mGxNGP6)?

**Comment by ThexXTURBOXx** [comment]
Of course, yes! I joined right now
