### ISSUE TITLE
window is freezing all the time

### ISSUE THREAD

**Issue by panteLx** [ShadyThGod/altus#27]
watch title :/

**Comment by ShadyThGod** [comment]
Please give me more information about your system. Mainly OS and RAM.
Because it's working fine on my Windows 10 machine with 8GB RAM.

**Comment by panteLx** [comment]
Win10, 16gb DDR4 RAM - freezing if I sent a message... sometimes it freezes even before I sent something

**Comment by panteLx** [comment]
oh and there is a wrong text in your readme (check latest version)

**Comment by ShadyThGod** [comment]
Is WhatsApp freezing or is the whole app freezing?
Also, can you elaborate on the wrong text?

**Comment by panteLx** [comment]
https://github.com/ShadyThGod/altus/blob/master/README.md#latest-releases check this line

whatsapp is freezing - i can still switch between my two instances of whatsapp but i'm not able to sent messages. on both instances. seems weired :D

**Comment by ShadyThGod** [comment]
Thanks for letting me know about README, I've fixed it.

About the freezing, since when has it been happening? Also, is there any way I can reproduce this?

**Comment by panteLx** [comment]
well... i think its since a week or smth like that. idk so far

I really dont know how to reproduce it because its random af XD

**Comment by ShadyThGod** [comment]
The thing I haven't experienced anything like this at all. So, I don't even know how to reproduce this. And without reproducing the issue, it's almost impossible to fix this.

**Comment by panteLx** [comment]
havent seen that issue the past few days. maybe its a weired bug with my pc.

**Comment by hradec** [comment]
This is happening to me constantly. I just installed Altus using the appimage, and it seems to work fine until I add my whatsapp account. After that, the window freezes and I can't click on anything... nothing happens. 

Weirdly enough, I see new messages arriving to me... So it seems the UI is updating and running, but I can't interact with it!

By disabling the custom titlebar, I'm able to move the window now, and access the menu (since now its the system window menu). But everything below the menu remains frozen for interaction, either by using the mouse or keyboard! 

I'm running Arch Linux, with Deepin desktop.
